In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/Users/thiru/Documents/My_Documentation/ML_and_AI/dataet/Iris.csv')

In [3]:
iris_features = data.drop(columns=['Species'])

In [4]:
mean = iris_features.mean()
mean

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [5]:
standard = iris_features.std()
standard

Id               43.445368
SepalLengthCm     0.828066
SepalWidthCm      0.433594
PetalLengthCm     1.764420
PetalWidthCm      0.763161
dtype: float64

In [6]:
features = iris_features

# Step 1 — Standardize datasett

In [7]:
features = (features-mean)/standard 
features

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   -1.714797      -0.897674      1.028611      -1.336794     -1.308593
1   -1.691780      -1.139200     -0.124540      -1.336794     -1.308593
2   -1.668762      -1.380727      0.336720      -1.393470     -1.308593
3   -1.645745      -1.501490      0.106090      -1.280118     -1.308593
4   -1.622728      -1.018437      1.259242      -1.336794     -1.308593
..        ...            ...           ...            ...           ...
145  1.622728       1.034539     -0.124540       0.816888      1.443121
146  1.645745       0.551486     -1.277692       0.703536      0.918985
147  1.668762       0.793012     -0.124540       0.816888      1.050019
148  1.691780       0.430722      0.797981       0.930239      1.443121
149  1.714797       0.068433     -0.124540       0.760212      0.787951

[150 rows x 5 columns]

In [8]:
features = features.to_numpy()
features

array([[-1.71479731e+00, -8.97673879e-01,  1.02861128e+00,
        -1.33679402e+00, -1.30859282e+00],
       [-1.69177989e+00, -1.13920048e+00, -1.24540379e-01,
        -1.33679402e+00, -1.30859282e+00],
       [-1.66876248e+00, -1.38072709e+00,  3.36720285e-01,
        -1.39346985e+00, -1.30859282e+00],
       [-1.64574507e+00, -1.50149039e+00,  1.06089953e-01,
        -1.28011819e+00, -1.30859282e+00],
       [-1.62272765e+00, -1.01843718e+00,  1.25924161e+00,
        -1.33679402e+00, -1.30859282e+00],
       [-1.59971024e+00, -5.35383973e-01,  1.95113261e+00,
        -1.16676652e+00, -1.04652483e+00],
       [-1.57669283e+00, -1.50149039e+00,  7.97980949e-01,
        -1.33679402e+00, -1.17755883e+00],
       [-1.55367541e+00, -1.01843718e+00,  7.97980949e-01,
        -1.28011819e+00, -1.30859282e+00],
       [-1.53065800e+00, -1.74301699e+00, -3.55170711e-01,
        -1.33679402e+00, -1.30859282e+00],
       [-1.50764058e+00, -1.13920048e+00,  1.06089953e-01,
        -1.28011819e+00

# Step 2 — Compute Covariance Matrix

In [10]:
def covariance_matrix(X,n_rows):
      covariance_matrix = sum([X[i].reshape(-1,1) @ X[i].reshape(1,-1)for i in range(n_rows)])/ n_rows
      return covariance_matrix

covariance_matrix(features, 150)



array([[ 0.99333333,  0.71189843, -0.39507729,  0.87686234,  0.89376019],
       [ 0.71189843,  0.99333333, -0.10864012,  0.86594246,  0.81250061],
       [-0.39507729, -0.10864012,  0.99333333, -0.41771266, -0.35416713],
       [ 0.87686234,  0.86594246, -0.41771266,  0.99333333,  0.95633872],
       [ 0.89376019,  0.81250061, -0.35416713,  0.95633872,  0.99333333]])

# Step 3 — Derive Eigenvectors and Eigenvalues of the Covariance matrix


In [12]:
def eigen_vectors(X, n_rows):
  C = covariance_matrix(X, n_rows)
  eigen_vectors = np.linalg.eig(C)
  return eigen_vectors

# the function returns two arrays - the first are the eigen values and the second the eigen vectors
eigen_values, eigen_vectors = eigen_vectors(features, 150)

# Step 4 — Sort the Eigenvalues and Eigenvectors


In [13]:
#sort eigenvalues from smallest to greatest magnitude using argsort function

sort = np.argsort(eigen_values)[::-1]

# use sort array to order eigenvectors

principal_components = eigen_vectors[:,sort]

principal_components

array([[-0.48136016, -0.02275157, -0.67406853,  0.55978662, -0.0067323 ],
       [-0.44844975,  0.38285827,  0.64520569,  0.40999945,  0.26061932],
       [ 0.23195044,  0.92007839, -0.27427786, -0.09491665, -0.12416613],
       [-0.51079205,  0.03074857,  0.13238322, -0.28817343, -0.79848404],
       [-0.5024696 ,  0.07356757, -0.19127876, -0.65305918,  0.52824072]])

# Step 5 — Return the Principal Components


In [15]:
def PCA_from_Scratch(X, n_rows, n_components):
  C = sum([X[i].reshape(-1,1) @ X[i].reshape(1,-1)for i in range(n_rows)])/ n_rows
  eigen_values, eigen_vectors  = np.linalg.eig(C)
  sort = np.argsort(eigen_values)[::-1]
  principal_components = eigen_vectors[:,sort]
  return principal_components[:n_components]

PCA_from_Scratch(features, 150,3)

array([[-0.48136016, -0.02275157, -0.67406853,  0.55978662, -0.0067323 ],
       [-0.44844975,  0.38285827,  0.64520569,  0.40999945,  0.26061932],
       [ 0.23195044,  0.92007839, -0.27427786, -0.09491665, -0.12416613]])

# Step 6 — Project the data on the principal components

In [19]:
def transform(X,principal_components):
  X = X.copy()
  X_proj = X.dot(principal_components.T)
  return X_proj


# transforming the iris dataset from four dimensions to two dimensions

X_transform = transform(features,principal_components)

X_transform

array([[-5.87005474e-01,  1.99855019e-01, -1.21643671e+00,
         2.41459252e+00,  7.80595939e-01],
       [ 1.84713216e-01, -6.46957608e-01, -1.11703725e+00,
         2.24275088e+00,  9.71835289e-01],
       [-1.63519012e-01, -4.75379274e-01, -1.45505587e+00,
         2.30096281e+00,  8.91284518e-01],
       [ 4.70622740e-02, -6.34266537e-01, -1.50833085e+00,
         2.22229587e+00,  8.40924042e-01],
       [-7.84037231e-01,  2.61135180e-01, -1.36944962e+00,
         2.39438236e+00,  6.81334789e-01],
       [-1.17907426e+00,  1.02017712e+00, -1.15811269e+00,
         2.23081869e+00,  6.00359191e-01],
       [-4.85167204e-01, -2.07908057e-01, -1.69297503e+00,
         2.19032321e+00,  7.80113501e-01],
       [-4.74628556e-01, -4.42022254e-02, -1.23229881e+00,
         2.28171538e+00,  6.97854834e-01],
       [ 2.76353980e-01, -1.09919283e+00, -1.57196669e+00,
         2.11135301e+00,  8.90569810e-01],
       [-2.67762257e-02, -5.91643762e-01, -1.12669235e+00,
         2.26752165e+00